### ISSUE TITLE
Skip Chat - routing of status messages to each chat window/conversation ID

### ISSUE THREAD

**Issue by AN-BC** [MemberJunction/MJ#101]
** Current Behavior **
1) Right now when you have a conversation with Skip things work great in terms of the status updates going into the chat window so long as you don't refresh the chat window. If you do, you lose the real-time streaming updates and have no indication that a request is in progress. Need to fix this so that we show a request is in progress with some kind of status message if we are in that state and we've come back to a conversation and aren't in the midst of a real time status update

2) If you have multiple chats going at same time, which is supported up and down the stack (they have their own conversation IDs), the streaming update from Skip API -> MJAPI -> UI can overlap. And they would be displayed in both chat windows incorrectly. Actual Conversation Detail records would not be displayed in the wrong conversation but the real time, non-persisted streaming updates from the Skip API -> MJAPI -> UI would appear in all chat windows in parallel. We need to simply filter on what we show in each chat window based on the conversation ID. Right now we pass session ID up and down the stack for our GraphQL subscription functionalty, which ensures messages go to the right client, which is important. On top of that we need to make sure the Conversation ID is included in Skip update messages. I think this is actually already the case, we just aren't paying attention to it. If that's the case, this is purely a simple UI update. If not, we have to add the Conversation ID to the payload for these subscription updates from Skip, which is pretty easy, and then pay attention to it in the skip UI.

@JS-BC  might be a good one for you post 1.0, this isn't super critical right now

**Comment by AN-BC** [comment]
@JS-BC  it turns out we are **not** passing the conversation ID back up the chain when we do a pubsub (graphql real time mechanism to update a client subscriber). Here's where we do this in the code:

https://github.com/MemberJunction/MJ/blob/e08cf6875d3659a04795cd8f4e7fa6fb1552ec7b/packages/MJServer/src/resolvers/AskSkipResolver.ts#L453

To fix this, we need to update the payload a bit and modify the message to include the actual message which we pass along unadultered, but also package in the conversation ID and the `JSON.stringify` it and then on the client side when we get the messages updates (code link below) we JSON.parse it and then unpack the message but check the conversation id to make sure it matches the conversation ID we're displaying:

https://github.com/MemberJunction/MJ/blob/e08cf6875d3659a04795cd8f4e7fa6fb1552ec7b/packages/Angular/ask-skip/src/lib/skip-chat/skip-chat.component.ts#L111

**Comment by hiltongr** [comment]
Closed per prior status updates
