### ISSUE TITLE
Finish Support for Virtual Entities

### ISSUE THREAD

**Issue by AN-BC** [MemberJunction/MJ#106]
The architecture currently supports virtual entities in concept. The metadata supports it and you can manually construct a virtual entity by specifying a pseudo-base-table and creating a custom base view. The base table is ignored in this situation and the CodeGen tool uses the custom base view provided to do metadata work. 

This works, but is a bit of a hack. The intent is to better support virtual entities directly as follows:

1. An admin can create a virtual entity manually in the UI by simply defining the entity name and providing the base view for it. Base Table won't be required in this case. Also, the Admin would populate one or more Entity Field records to specify the primary key for the virtual entity.
2. From there, we need to update the CodeGenLib to implement support for virtual entities properly. The vast majority of the existing code will work fine but we have to test it out
3. Write some documentation explaining the use of virtual entities so people can take advantage of this concept.

**Comment by hiltongr** [comment]
Rolled it in MemberJunction 2.5x
