### ISSUE TITLE
Setup pm2 for the MJCodeGenAPI sub-process and test

### ISSUE THREAD

**Issue by AN-BC** [MemberJunction/MJ#127]
Per #126

**Comment by AN-BC** [comment]
Actually this commit is what is most interesting within that PR @cadam11 

https://github.com/MemberJunction/MJ/pull/126/commits/b4b9d1351cda0d6750df9d14c1270689bd276f3d

**Comment by cadam11** [comment]
@AN-BC This is deployed and running in the CDP stage environment

**Comment by AN-BC** [comment]
@cadam11 should this be closed?
