### ISSUE TITLE
Allow uniqueidentiifer fields that are not primary keys to be updateable

### ISSUE THREAD

**Issue by JS-BC** [MemberJunction/MJ#159]
Some context:

"Non-critical issue/question - not enough to make me run the upgrade to see if it's already been fixed, but I have a uniqueidentifier type field in SQL that isn't the primary key but seems to have been left as read only by not including it in the generated update stored procedure. The EntityField record is marked AllowUpdateAPI = 1 and generally looks the same as other working fields.
 
Is there anything intentionally blocking uniqueidentifier fields from being updated with a new GUID?
 
I don't actually need to update it in this case and wasn't intending to, but ran into this accidentally so I don't need to fix it at the moment. There's a chance I will revisit that decision in the future, though." - Dray

"I'm not 100% sure but I think uniqueidentiifer fields might have an assumption of being server side generated upon record creation and therefore not editable even if you have `AllowUpdateAPI` set to 1" - Amith

"when we generate the stored procedure for the entity, if the field is a uniqueidentiifer we assume its an autoGeneratedPrimaryKey and do not include it as one of the fields to update" - Jonathan

**Comment by cadam11** [comment]
Confirmed that this work in MJ 2.6.1. The FK field is rendered as a drop-down selection that shows the FK record's Name, but stores the ID when selected. It can be later edited to change to another FK parent record.
