### ISSUE TITLE
Errors in entity_subclasses.ts file of GeneratedEntities

### ISSUE THREAD

**Issue by HiteshDhamecha** [MemberJunction/MJ#202]
Hello Team, @hiltongr ,

After running the CodeGen , I am getting errors inside **entity_subclasses.ts file of GeneratedEntities** 

Here are the scrennshots : 
![image](https://github.com/MemberJunction/MJ/assets/125297107/23c05ef4-36c9-46f8-bc74-a412dfbeaf88)

**Comment by cadam11** [comment]
Looks like a bug in Codegen– the `-` in the column name isn't being escaped (or removed)

**Comment by cadam11** [comment]
Relevant code is  https://github.com/MemberJunction/MJ/blob/7993ce753fcdf93a1adf388e119e1a1b519a62af/packages/MJCore/src/generic/entityInfo.ts#L377

This could also replace `-` characters
