### ISSUE TITLE
User Authorization Error in MJExplorer

### ISSUE THREAD

**Issue by HiteshDhamecha** [MemberJunction/MJ#238]
**Describe the bug**
After entering valid login credentials into the MJExplorer application, I am getting an authorization error.

**To Reproduce**
1. Login to MJExplorer using MSAL
2. Open browser developer tools

**Screenshots**
Attaching error screenshot 
![image](https://github.com/MemberJunction/MJ/assets/168705280/cfd1057a-14d7-4615-9f1e-1124e623922a)

**Comment by cadam11** [comment]
This was an artifact of a distribution zip for 1.4.0 that incorrectly contained 1.3.3 packages. The old zip has been removed and a new one added to the releases channel. The links on https://docs.memberjunction.org/docs/downloads have been updated to point to the correct zip.
