### ISSUE TITLE
Update return type of BaseEntity.Save and Delete functions from a boolean to EntityTransactionResultType

### ISSUE THREAD

**Issue by JS-BC** [MemberJunction/MJ#246]
Purpose: In the future, we want to add the ability to display error messages to a user if a save attempt fails (https://github.com/MemberJunction/MJ/issues/243). Currently, if a save attempt fails due to validation errors, an exception is thrown containing reasons why, i.e. Validation Error Messages. Rather than wrapping every save attempt client side in a try-catch block, it would be easier for us to get error messages and display them if the save attempt returns an object similar to the RunViewResult type that contains a Success, Result, and ErrorMessages properties. 

The EntityTransactionResultType type could be defined as below:

Success: Boolean
- Returns true if the save attempt was successful, false otherwise

ErrorMessages: String[]
- If a save attempt was unsuccessful, this property would be populated with the reason(s) why the save attempt failed. 

ValidationErrorMessages: any[]
- This would hold data that current exceptions contain, such as the field where the validation error was thrown as well as the field's value, etc. Mainly for debugging purposes. This would only be populated if the save attempt was not successful 

WarningMessages: String[]
- If a save attempt was successful, but something unexpected happened, e.g. not all records of a view were added into a list, then this property would be populated with messages explaining what happened

Thoughts? @AN-BC

**Comment by AN-BC** [comment]
@JS-BC let's make this "EntityTransactionResultType" instead and that way we can use this for both `Save` and `Delete` basically that would cover Create/Update/Delete scenarios, or all transactions.

**Comment by JS-BC** [comment]
@AN-BC This isnt needed now that we have `BaseEntity.LatestResult` right?

**Comment by AN-BC** [comment]
@JS-BC  yup - that's right, I'm closing this issue. Thanks.
