### ISSUE TITLE
Can't Get Setup

### ISSUE THREAD

**Issue by Chunter-me** [MemberJunction/MJ#33]
Walking through the install instructions and the installMJ.js keeps failing with the Code Gen:

`STARTING MJ CodeGen Run... @ 3/24/2024, 8:42:28 AM
Initializing Data Source...
Error during Data Source initialization ConnectionError: Failed to connect to 127.0.0.1,8700:1433 - getaddrinfo ENOTFOUND 127.0.0.1,8700
    at connectListener (D:\Repos\member-junction\install\CodeGen\node_modules\mssql\lib\tedious\connection-pool.js:85:17)
    at Connection.onConnect (D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:1759:9)
    at Object.onceWrapper (node:events:629:26)
    at Connection.emit (node:events:514:28)
    at Connection.emit (D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
    at Connection.socketError (D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:2309:12)
    at D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:2098:37
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ESOCKET',
  originalError: ConnectionError: Failed to connect to 127.0.0.1,8700:1433 - getaddrinfo ENOTFOUND 127.0.0.1,8700
      at Connection.socketError (D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:2309:28)
      at D:\Repos\member-junction\install\CodeGen\node_modules\tedious\src\connection.ts:2098:37
      at processTicksAndRejections (node:internal/process/task_queues:77:11) {
    code: 'ESOCKET'
  }
}`

I'm guessing this is due to me running my SQL Server through Docker Desktop using a Windows SQL Server container. The DB is up and running without any connection issues I can find. The user creation and initial scripts ran just fine form steps 1 and 2. I have also validation I can login as the users from step 2. I'm using Azure Data Studio.

I am also assuming that with the install.config.json the mjAPILogin is suppose to be the MJ_Connect_Dev created in step two?

As well in the installMJ.js's renameFolderToMJ_BASE(dbDatabase) function. If I am running the installer for a second/third time due to it failing or just am on the same folder this step will fail every time as instead of just creating a new folder or checking for an existing folder you as assuming that the install it being run the first time and your renaming a folder, not sure if this does cause issues downstream.

**Comment by cadam11** [comment]
Looking at the Docker error, it seems like it's having a problem connecting to the container. You may need to double-check the Docker/host port mapping, as well as the `.env` config in the `packages/CodeGen` dir.  Feel free to share your config to get some extra 👀 on it.

If I run a local SQL Server with this command (this is on M1 Mac, so YMMV).

```shell
docker run --rm -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Unbre@kab1eP@ssw0rd" -p 1433:1433 --name sql --hostname sql --platform linux/amd64 -v `pwd`/sql_server:/var/opt/mssql mcr.microsoft.com/mssql/server:2022-latest
```

Then run the setup scripts (`MJ_BASE_Structure`, then `MJ_BASE_Dataset`). Here's an example of working `.env`

```
# -- Docker -- #
DB_HOST='localhost'
DB_PORT=1433
DB_USERNAME='MJ_CodeGen_Dev'
DB_PASSWORD='Unbre@kab1eP@ssw0rd'
DB_DATABASE='cdp'
DB_TRUST_SERVER_CERTIFICATE=true
```

I'm able to successfully connect when running the `CodeGen` package.

**Comment by Chunter-me** [comment]
Ah, ok I see the issue. I've gotten so dam use to copy/pasting 127.0.0.1,#### as the server/host value to other things that I didn't even notice the 1433 Post value.. ugh... sorry.
