### ISSUE TITLE
Scheduled Tasks Module for Running Recurring Jobs

### ISSUE THREAD

**Issue by cadam11** [MemberJunction/MJ#343]
Define a ScheduledTaskBase class as usual. For the scheduled task type, we will have an enumeration of types/names, with each type having sub-classes of the base class that implement the desired functionality. Implement a sub-class specifically for running the external change detection and add a new scheduled task type record for this.

The Scheduled Tasks entity will have rows indicating the task type to run, frequency, active status, etc. Scheduled Task Runs will log when a task starts, ends, fails, etc.

This setup can be used for running any recurring jobs. We will include a field in the Scheduled Tasks entity to determine where the task runs, such as a deployment name. This way, the software configured in each environment will only pick up matching tasks, based on environment variables.

- Define the ScheduledTaskBase class and the enumeration for task types.
- Implement the specific sub-classes for different tasks.
- Create the Scheduled Tasks entity with necessary fields.
- Create the Scheduled Task Runs entity to log task executions.

**Comment by AN-BC** [comment]
This is now resolved via the `Scheduled Actions` project
