### ISSUE TITLE
Unable to use Promise.all to create entity records 

### ISSUE THREAD

**Issue by JS-BC** [MemberJunction/MJ#554]
Given this block of code: 
![image](https://github.com/user-attachments/assets/708e65ac-447b-495e-bba3-db2991b64292)

I get the following error(s): 
![image](https://github.com/user-attachments/assets/c545d3da-602d-4295-ac95-6389c4d62065)

But the above succeeds if I iterate the list using a for-of loop:
![image](https://github.com/user-attachments/assets/30b14c57-1624-4231-aab6-5d960ec9ba21)

**Comment by AN-BC** [comment]
@JS-BC this is odd since you're using an await within each promise and the code shouldn't be blocking for running these in parallel. I wonder if @cadam11 might see anything wrong with how the `Promise.All` is constructed?

**Comment by JS-BC** [comment]
@AN-BC @cadam11 I think this is less an MJ or typescript issue and more an issue with the underlying library we're using to make queries to the DB. Perhaps the library is unable to handle 100s or 1000s of queries at a time

**Comment by AN-BC** [comment]
Perhaps, but I doubt that.

**Comment by cadam11** [comment]
The `Promise.all()` call is fine in itself, although I could strongly suggest using a helper function to manage concurrency limits and avoid exhausting thread pools or hitting memory limits.

**Comment by AN-BC** [comment]
That makes sense, if the array if very large that could be causing the issue, maybe do this in batches of 10/20/50 etc and control that with a batch size variable instead of doing them all at once.

**Comment by JS-BC** [comment]
Splicing the array into smaller chunks does the trick
