### ISSUE TITLE
URL doesn't change when tabs on a form are clicked in MJ Explorer

### ISSUE THREAD

**Issue by AN-BC** [MemberJunction/MJ#611]
When you click on a tab on a record viewing form in MJ Explorer, the URL is supposed to update to reflect that, and until some recent version, it worked. This allowed deep linking down to the tab level and was very useful for bookmarking and sharing links. I suspect this is still in the code but somehow an event handler got unwired or something like that. Should be easy to diagnose and fix. 

@JS-BC  can you review and knock this out please?

**Comment by JS-BC** [comment]
closed with https://github.com/MemberJunction/MJ/pull/621
