### ISSUE TITLE
Add more User Roles

### ISSUE THREAD

**Issue by JS-BC** [MemberJunction/MJ#671]
Currently, there are 3 user roles defined in MJ:
- UI: Essentially grants read only access to all resources
- Developer: Allows the user to perform any CRUD operation on all entites in the system
- Integration: Intended for server side programs to allow them to use the MJ framework. Same level of permissions and access as the Developer tole

So out of the box, an admin only has the choice to give a user either read only access to all resources or give them admin-level access as well. We should create more roles that target more specific levels of access. Below are some examples:

### Basic:
- The basic role would prevent a user from performing any CRUD operations on core entities (i.e. an entity in the __mj schema) except for the following entities:
  - Lists
  - List Details
  - Dashboards,
  - Reports
  - All Category entities
  - Queries
  - User favorites
  - User Notifications
  - User Views
  - Workspaces 
  - Workspace Items

Basically, any entities that are required to use MJ at a basic level. Modifying core entity data or using advanced features, such as running duplicate record detection or executing actions would not be allowed. Whenever a new entity is created, the Basic role will have access unless it is a core entity, in which they would only have read only access.

### Admin (Name TBD)
- The Admin role is a super set of the basic role in that it has permissions to modify any core entity except for the following:
  - Datasets
  - Dataset Items
  - Entities
  - Entity Fields
  - Entity Field Values
  - Entity Permissions
  - Entity Relationships
  - Entity Settings
  - Fly Schemas
  - Record Changes
  - Resource Types
 
Basically, any entity that is "core" to MJ, i.e. any entity CodeGen depends to maintain the metadata layer. The idea being that admins should be able to access and change anything data related, but things that are crucial to MJ operating smoothly are restricted away. Whenever a new entity is created, admins would have read and write access to it.

### Sys Admins (Name TBD)
- Super admins are an exact copy of the Developer role, except with a more intuitive name. This would allow us to reserve the Developer role to actual developers of the system. Just like the Developer role, Sys Admins would have complete access to all current and future entities

### Some Additional Notes
- By default, users that CodeGen create would be given the Sys Admin role, whereas users that MJServer create would be given the Basic role

@AN-BC @hiltongr  Please review

**Comment by AN-BC** [comment]
Only issue with removing an existing role that we ship is backwards compatibility so I’d suggest we don’t do that for that reason. I also could envision the UI role being used as another level above basic in some orgs.
