### ISSUE TITLE
Dataset Caching - Deleting records from a dataset item fails to result in a refreshed client-side dataset

### ISSUE THREAD

**Issue by AN-BC** [MemberJunction/MJ#96]
If you delete a record in a dataset item on the server, this does **not** result in the datasetitem/dataset being refreshed on the client. 

The reason - DatasetItem checking for if it is up to date gets the `MAX` date from the combined set of data across all of its dataset items. This is great for new and updated records in those entities, but if records are deleted, that doesn't affect the date calculation.

A possible fix is that we use the `RecordChanges` functionality and we look for deleted records in there and include that in the checking query to determine the max updated date for each dataset and then roll that up for the dataset.

The issue with that approach is:

1. If a change is made via the back-end, no Record Changes metadata will be generated, this only happens if (a) TrackChanges is turned on for the entity in question and (b) if the deletion occurs via the BaseEntity object model.
2. If an entity used in a DatasetItem does not have TrackChanges turned on at all

These two weaknesses in that approach might warrant exploration of other approaches possibly including something like a trigger auto-generated and maintained on tables that are defined in a DatasetItem and that trigger would automatically update the UpdatedAt field on all rows in the table whenever a DELETE operation occurs on **any** row in the table. The downside to that of course is the row-specific UpdatedAt no longer properly reflects the actual updated date/time for that row.

What other solutions could be good for this @cadam11 @JS-BC  @hiltongr ?

**Comment by cadam11** [comment]
Could use a soft-delete strategy– setting a `DeletedAt` time stamp as a flag instead of actually deleting the record. 

Another approach is to emit mutation events via Graphql subscription. The client would subscribe to a field that gets data any time there's a delete mutation and uses that to invalidate its cache (which can be as specific as the details in the event allow).

**Comment by AN-BC** [comment]
@cadam11  I think a soft-delete strategy could work in some cases but since Datasets are generalized and need to support basically any entity I think we have a bit of a challenge here. One other approach would be the RecordChange metadata and perhaps require `TrackRecordChanges` to be on for an entity to be included within a Dataset? In that case we would just look at the max(date) in the Record Changes table for this entity to calc the biggest date and that includes deletes. Thoughts on that approach?
